api-private.swagger.yaml

to be used by Drupal to talk to the Node application

ITB-286 add swagger definition for private API

---

api.swagger.yaml

https://mermade.org.uk/openapi-converter

Initial output of conversion

---

api.swagger.yaml

https://projects.invisionapp.com/share/QXFR933NG6Z#/screens/277949805

group category search and autocomplete

---

api.swagger.yaml

Remove 201 response for `PUT /groups/{group_id}/members/{user_id}`

INVGOV-7883

---

api.swagger.yaml

Added 2 new GET endpoints:
/manuals - Get all manual pages
/manuals/{manual_page_id} - Get a manual Page
Added a new schema
manual-page-schema
Swagger editor has automatically made some changes:
long description lines have been moved only new lines with >- syntax
removed some white-space
fixed some tabbing alignment

ILABS-1 Add Manual Page endpoints

---

api.swagger.yaml

Revert "ILABS-1 Add Manual Page endpoints"

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-9100

INVGOV-9100 Added user profiles swagger

---

analytics.swagger.yml

copied  matomo-poc swagger to this place

add matomo-poc defs

---

api.swagger.yaml

Is it okay to allow this call anonymously? Amazon can't send an API key header to authenticate the request for the health check.

INVGOV-9839 add status endpoint

---

api.swagger.yaml

[ITB-1012](https://io1dev.atlassian.net/browse/ITB-1012)
[ITB-978](https://io1dev.atlassian.net/browse/ITB-978)

ITB-1012: Swagger documentation for ITB-978

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/EE-15

EE-15 Register notifications swagger update

---

api.swagger.yaml

[ITB-1011](https://io1dev.atlassian.net/browse/ITB-1011)
[ITB-981](https://io1dev.atlassian.net/browse/ITB-981)

ITB-1011: Add callback endpoint to Swagger doc

---

api-private.swagger.yaml

[ITB-1010](https://io1dev.atlassian.net/browse/ITB-1010)
[ITB-979](https://io1dev.atlassian.net/browse/ITB-979)

ITB-1010: Swagger changes for ITB-979

---

api.swagger.yaml

[PDF-9](https://io1dev.atlassian.net/browse/PDF-9)
[PDF-21](https://io1dev.atlassian.net/browse/PDF-21)

PDF-21: Remove unnecessary request/response data

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/PDF-32

PDF-32 Add 401 response code for pdf-export/ID endpoint

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/PDF-25

PDF-25 Add error response handling

---

api-private.swagger.yaml

https://io1dev.atlassian.net/browse/PDF-28

PDF-28 Move latest revision property to a body

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/EE-235

EE-235 Clear all notifications swagger

---

api-private.swagger.yaml

https://io1dev.atlassian.net/browse/PDF-97

PDF-97: Add optional use_export_service parameter

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/SCBLOG-63

SCBLOG-63 Add authname to /users GET and POST

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10386

INVGOV-10386 Fixes to swagger schemas to remove minor mismatches

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10595

INVGOV-10595: Update team list schema to reflect NINJA

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10301
Depends on approval of #183

INVGOV-10301 chnaged group-schema.author_uuid to read only

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/IB-3234
https://dev.invotra.com/?url=https://raw.githubusercontent.com/invotra/api/IB-3234-01.SWAGGER-4.49/api.swagger.yaml#/blogs

IB-3234 Added 9 Content Types - Batch 01

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10810

IB-3284 Added /group_polls

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10702

INVGOV-10702 Added /job_roles/list

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10573

INVGOV-10573 Add Cognito authnames support

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/IB-3313

IB-3313 Added /group/ID/document_folders

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10881

INVGOV-10881 limit parameter wording change for >100

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10921

INVGOV-10921 Add 403 to GET /manuals/uuid

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10926

INVGOV-10926 Update Locations Frisby tests

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-11689

INVGOV-11689 API logging endpoint from FE

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-11016

INVGOV-11016 Frisby Test Failing - Sessions / Authenticate by API key

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10907

INVGOV-10907 GET /feeds.topic renamed groups->group

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-10907

INVGOV-10907 Revert

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/CRC-11

CRC-11 API updates - Review date

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/BCP-11

BCP-11 API must adhere to read only access

---

.github/workflows/build_ts_client.yml

https://io1dev.atlassian.net/browse/INVGOV-12398

INVGOV-12398 Swagger fix github action set-env not allowed

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-12583

INVGOV-12583 Static content widget: Displaying unpublished teams

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13058

INVGOV-13058 Manage groups page - Search is showing results from desc

---

api.swagger.yaml

Revert "INVGOV-13058 Manage groups page - Search is showing results from desc"

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13031

INVGOV-13031 Sorting by Admin is not sorting correctly

---

api.swagger.yaml

Just did:
git merge origin/AGR-11.SWAGGER-5.10

AGR.SWAGGER-5.14

---

client/typescript-axios/build/package.json

https://io1dev.atlassian.net/browse/INVGOV-13143

INVGOV-13143 Update version of packages in Swagger code

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13264

INVGOV-13264 API - Add /comments/{comment_id} EP

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13307

INVGOV-13307 SWAGGER-5.14-new some EPs missing security object

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13343

INVGOV-13343 Change user endpoint to call all information required

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13340

INVGOV-13322 Added swagger for comment author properties

---

api.swagger.yaml

Revert "INVGOV-13322 Added swagger for comment author properties"

---

api.swagger.yaml

Revert "INVGOV-13343 Change user endpoint to call all information required"

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/IMP-28

IMP-28 Add external id filter to /list and /search endpoints

---

api.swagger.yaml

Revert "Revert "INVGOV-13343 Change user endpoint to call all information required""

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13205

INVGOV-13205 /save/{content_id} Node.js API endpoint - Swagger changes

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13220

INVGOV-13220 /like/{content_id} Node.js API endpoint

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/PCS-13

PCS-13 API: Poll Content type to be Section Based

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/CWR-13

CWR-13 API: SSM to Clear Webforms Results

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13205

INVGOV-13205 fix save/unsave response schema

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13556

INVGOV-13556 Added content title & body to feed swagger definition

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13581

INVGOV-13581 API content types owner/author trimmed user schema remove

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/ITB-1566

SWAGGER-5.18 POST /users - is_line_manager should be read only

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13661

INVGOV-13661 Changes inadvertently reverted from SWAGGER-5.16 branch

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13646

INVGOV-13646 API posts required properties missing

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13731

INVGOV-13731 Manage content - Manual pages are being classed as Manuals

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13793

INVGOV-13793 Error message while performing Bulk Action on post

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/GFN-23

GFN-23 API: Manage Groups Notifications

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/BWM-14

BWM-14 API: Multiple Blogs Widget

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-13388

INVGOV-13388 /locations/ missing Node.js API endpoint

---

api.swagger.yaml

https://dev.invotra.com/?url=https://raw.githubusercontent.com/invotra/api/INVGOV-13958.SWAGGER-5.21/api.swagger.yaml
https://io1dev.atlassian.net/browse/INVGOV-13958

INVGOV-13958 API feeds required properties missing

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-14007
https://dev.invotra.com/?url=https://raw.githubusercontent.com/invotra/api/INVGOV-14007.SWAGGER-5.22/api.swagger.yaml

INVGOV-14007 API Schema validation failures 5.22 missing props

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-14050

INVGOV-14050 Bulk update - author and owner

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/ITB-1610

ITB-1610 Frisby test failures - Search highlights basic tests

---

api.swagger.yaml

https://dev.invotra.com/?url=https://raw.githubusercontent.com/invotra/api/INVGOV-13430.SWAGGER-5.18/api.swagger.yaml
https://io1dev.atlassian.net/browse/INVGOV-13430

INVGOV-13430 POST /galleries missing

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/PP-24

PP-24 add franchise setting field in administration schema

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/PP-20

PP-20 get and set read confirmation for policy

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-14108

INVGOV-14108 return custom content name

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/UCC-12

UCC-12 add more filtering option for files

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/UCC-12

UCC-12 return internal id for file

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/PP-23

PP-23 expose api for getting users or policies

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/ECOM-22

ECOM-22 return worldpay setting configuration for administration

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/PP-82

PP-82.SWAGGER

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/PP-84

PP-84.SWAGGER

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/ECOM-77

ECOM-77 Add cc field

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/CT-64

CT-64 Timeframe field

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/CT-70

CT-70 Custom overlay tour properties added

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/PP-99

PP-99 Changed confirmed_revisions property

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/CT-75

CT-75 Checklist reporting

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/MSI-68 - swagger task
https://io1dev.atlassian.net/browse/MSI-67 - node task

MSI-68 Add message type property to post

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/CT-105

CT-105 Add pid to checklist status endpoint

---

api.swagger.yaml

Drupal changes fixed this issue

Revert "CT-105 Add pid to checklist status endpoint"

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/CT-105

CT-105 Add tasks ids to fetch status endpoint

---

api.swagger.yaml

New shape: https://io1dev.atlassian.net/browse/CT-100?focusedCommentId=321649

CT-100 Changed timeframe shape

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-15108

INVGOV-15108 Add user picture to response

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/MSI-62

MSI-62 Update user search schema to include integrations

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/MSI-65

MSI-65 handle new notification type

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/MSI-56

MSI-56 configure microsoft 365 search

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/MSI-44

MSI-44 Add share file endpoint

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-15065

INVGOV-15062 Remove group category from required fields list

---

api.swagger.yaml

Revert "INVGOV-15062 Remove group category from required fields list"

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/INVGOV-15085

INVGOV-15085 Add excluding body from search content param

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/MSI-64

MSI-64 Add microsoft file share endpoint

---

.github/workflows/build_ts_client.yml
client/typescript-axios/build/package.json

https://io1dev.atlassian.net/browse/INVGOV-15257
[INVGOV-15257]: https://io1dev.atlassian.net/browse/INVGOV-15257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

INVGOV-15257 Upgrade node to v16

---

api.swagger.yaml

https://io1dev.atlassian.net/browse/MSI-156

MSI-156 Add integrations to user mentions schema
